version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install system dependencies
          command: set -xe && apt-get -y update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

